# We are using travis to test the validity of the RDF and to deploy the files
# so we don't need a ruby or other language specific image
language: minimal
env:
  global:
  - secure: AnKLsCwsMJM7Xk0G946LP9z0CRyC7bQb1ilM+KbwHR/PNSQjkJMR6mKsNL5Z5BhZr3q9xEG76vg9Em1CjH2HTYtyvLf68bB8KxrC+kTU4ECqn7YDLk8inosWazSiZ3IkSISeNJyW9CzmrFEjpQQ9h9G/8aJJ2lEXnsoC4TduKkB2AQQXhTI9gzrf65+nCk9cF/nKVbwN1c2NEfgxf+mK2/6/gD7bYuZi+9zxd+ReF09nrshMhLP8DW+9lEsR6O51B6y9kOSnCCxy+6HqhBx1qEKVq1Xh1Lp8CJuDdgcq8hr8mb3o3lVWQwwduXy5w9p8gJh96lv+49F0AOKfZRsnflwpvVKejWqehfteq9bdRsARbtC/8w9sF40vKE08B1/bBljleW6+UlZ7+h554Wj+XxH7q+lw32j+6Xeihc6fnwH0SdG9zG8N1iQ4NwGn8d2pBT6P56Op68kQXPJChowZ1gtT8/YcKEGhV5VeBphntl4q2laaiA3Dw1KuuGm/e3w3/bgnokYn2lcN2ZTbMyKDu9nRUKDrRpdvAzicO2PzUsDwEjrMwIifTFN+Pj1nPe7It/KKOZud28ojlGcFLS7tbIsMw6XZroAmNCZdWKJe9MgLDROybsmLXkH1BfaChVRs/qU/wGAv3X3ZXn95xNroOXezfInPaCllLbyPZKXcy18=
  - secure: uiIXUOqTFIIyEweBEyrsqiFkQHdWf/wjbNIrdWpj+BUAVmu8h+gg7ao3TmehIf6Wh5SayV+tWkYcaTejqDnXLyTACYxNVIrP6yQxEAOuFv86HGXdnwFJmt82SEuNeKRkyEQX1sRatYEnAhUFaLKkI77PcJgq9DAUJh7tF3TNY/w+aVoMVhmPyeh2RrlymcQXok939qHGOzpDDVYfAPhziRITB1XsMx/zxGzXwrtcfRvTyzHewUSY98kMKCrfxsdLUNn+Cpfixcgoa1QUpOjYlMlC/HbZmsuyAxOLvPUIFnjtjLtC0IryTUUlgiS9XNCP7TVnZG/DF1K+Zca1HE51KoN2EyfJARxQpQ/dn4YMbbQATuRJUYY+sOZ/bl4sl3PXFSSvGhqOjcSYCw0D0nFsc3YW3bxYeTNkd4GYlByj8OFo8hCpRlo5LVD3f8ABSPMHQGt0Aik/MnAuoab9XgVPbnd+yusBZYX+Aqmm7Zj5chXcQlu9gdivxCk7O3KedXcvqYB4GEPpcmw+ERmAqB7i08H08usjTs2DLh3iJewzps6Qy+kkrq+YGwQXKaosc61OwC7c2oRBvNfJ7p55thiOqFR56AC1MvFXvayQbAnkeWSmQxIYNbLyqXcHSqQ7o+I0m9UlB3Ijkv8mdI8c0WTbZkzTxXqI+3GwSXXe5Ez1NoM=
  - secure: QJKVlyNNQu8F7QQwWUwphws9SX+8c5o4nVeH/45VkfUF1sMt1MFba+w0uRj3d5qw/DCzy1A2xNxFjnmoES3qwm/XrL1EWDGCb6QsE660lYs86/vF6kmLRkwt72NjtIPHLnKYj64Wpxsr7uvuvZY4nEcH4/XECTKtcP5AkNgRhGN8CXr4laZDNdXdbL5ncSzhs1iy/S6fGss9bKvnx6WenVBjzgqRMdhHT5yT11MkHLwYpgQMZvIlwlnBETTkjQDaD2PbkedvNvUGuY7fvk0zsgG/PMCWRLfDS1rIJJ//Jq5jozDE69GWbjzaH6fMSR2ZUVohgdNQZxslgg6Mbhvbm+kEVFtAbrJ9wKuN6EvaKlD+sHI/wpjayNJzf90dmRyLUBJdeWH+lKy6jvj+UU4Wvqz1yF5JPfg78HlJFmbZaiHzpvrktbExUCJYXRKvagUL+6dK7WOZTOzESulUeD+JDsdaBV5aoEMSeUXzZ8rAb6i896Qg0YNncWUS1/cslkPlfXpZJbtbEUtvh1W0Gm7Ln9HO5zsiA2eAR0h7ZlTnr7mfNBYP5wEWrS8nASX/ITFjniBmJ/n+ZAHW+b8XL5vXj4REbxxPHDeS20JI/3dpTNlWmHQmD5fJWdIPEAjTXb30Z11SpMxujldP2aHXlJqipDYh94s/VcKKuQIFd3EzH14=

services:
  - docker
jobs:
  include:
  - stage: test
    script:
    - docker pull stain/jena
    - shopt -s globstar
    - docker run -it --rm -v `pwd`:/rdf stain/jena riot -v --debug --validate --time
      **/*\.ttl
before_deploy:
  - openssl aes-256-cbc -K $encrypted_b6ce18fca7c2_key -iv $encrypted_b6ce18fca7c2_iv -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy\_rsa
  - ssh-add deploy\_rsa
  - echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  skip_cleanup: true
  script:  rsync -r --quiet --delete-after -aR activitytype/ flowobject/ foaf/ location/ time/ unit/ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIRECTORY/
  on:
    branch: master
